#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/infinix/X6739

PRODUCT_COPY_FILES += \
    vendor/infinix/X6739/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/035c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/035c0000000000000000000000000000.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/035c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/035c0000000000000000000000000000.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/05060000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05060000000000000000000000000000.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/05070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05070000000000000000000000000000.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/9e412fe49fe460a16bada5a0eeef369f.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9e412fe49fe460a16bada5a0eeef369f.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/ce4550edbcb1662566b006ebcb303050.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ce4550edbcb1662566b006ebcb303050.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin \
    vendor/infinix/X6739/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/infinix/X6739/proprietary/vendor/etc/.tp/.ht120.mtc:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.ht120.mtc \
    vendor/infinix/X6739/proprietary/vendor/etc/.tp/.thermal_policy_03:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_03 \
    vendor/infinix/X6739/proprietary/vendor/etc/.tp/.thermal_policy_08:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_08 \
    vendor/infinix/X6739/proprietary/vendor/etc/.tp/.thermal_policy_09:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_09 \
    vendor/infinix/X6739/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/infinix/X6739/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/infinix/X6739/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/anc_siq/cache_s5kgd2sp_17201766_front_d1300:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/cache_s5kgd2sp_17201766_front_d1300 \
    vendor/infinix/X6739/proprietary/vendor/etc/anc_siq/cache_s5khm6sx_17201842_back_d1300:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/cache_s5khm6sx_17201842_back_d1300 \
    vendor/infinix/X6739/proprietary/vendor/etc/anc_siq/dgain_mask_s5kgd2sp_17201766_front_d1300.bin:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/dgain_mask_s5kgd2sp_17201766_front_d1300.bin \
    vendor/infinix/X6739/proprietary/vendor/etc/anc_siq/dgain_mask_s5khm6sx_17201842_back_d1300.bin:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/dgain_mask_s5khm6sx_17201842_back_d1300.bin \
    vendor/infinix/X6739/proprietary/vendor/etc/anc_siq/siq_ocl_cache_s5kgd2sp_17201766_front_d1300:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/siq_ocl_cache_s5kgd2sp_17201766_front_d1300 \
    vendor/infinix/X6739/proprietary/vendor/etc/anc_siq/siq_ocl_cache_s5khm6sx_17201842_back_d1300:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/siq_ocl_cache_s5khm6sx_17201842_back_d1300 \
    vendor/infinix/X6739/proprietary/vendor/etc/anc_siq/superiq_model_s5kgd2sp_17201766_front_d1300:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/superiq_model_s5kgd2sp_17201766_front_d1300 \
    vendor/infinix/X6739/proprietary/vendor/etc/anc_siq/superiq_model_s5khm6sx_17201842_back_d1300:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/superiq_model_s5khm6sx_17201842_back_d1300 \
    vendor/infinix/X6739/proprietary/vendor/etc/apdb/APDB_MT6885_S01__W2417:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6885_S01__W2417 \
    vendor/infinix/X6739/proprietary/vendor/etc/apdb/APDB_MT6885_S01__W2417_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6885_S01__W2417_ENUM \
    vendor/infinix/X6739/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/cam3atms_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cam3atms_profiles.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/cust_color.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/cust_silky_brightness.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_silky_brightness.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/ecc_list_tran2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_tran2.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/factory.ini:$(TARGET_COPY_OUT_VENDOR)/etc/factory.ini \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-mediatek.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.3-service.transsion.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.3-service.transsion.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service.trustonic.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/android.hardware.sensors@2.0-service.multihal-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@2.0-service.multihal-mediatek.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.conninfra.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.conninfra.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.thermal_core.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_core.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/networksetting.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/networksetting.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/trustonic.mc_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.mc_kmsetkey_ca.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/vendor.goodix.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.goodix.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/vendor.transsion.hardware.trancam.trancamserver@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.transsion.hardware.trancam.trancamserver@1.0-service.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/infinix/X6739/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/infinix/X6739/proprietary/vendor/etc/nhw:$(TARGET_COPY_OUT_VENDOR)/etc/nhw \
    vendor/infinix/X6739/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/infinix/X6739/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/tran_camprofiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/tran_camprofiles.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/trancam_filelock.json:$(TARGET_COPY_OUT_VENDOR)/etc/trancam_filelock.json \
    vendor/infinix/X6739/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/infinix/X6739/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/infinix/X6739/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/infinix/X6739/proprietary/vendor/firmware/Conf_MultipleTest_00.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/Conf_MultipleTest_00.ini \
    vendor/infinix/X6739/proprietary/vendor/firmware/WIFI_RAM_CODE_soc3_0_1a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc3_0_1a_1.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw22xxx_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_fw.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw8622x_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_haptic.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw8622x_osc_rtp_12K_10s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_osc_rtp_12K_10s.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw8622x_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw8624_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_haptic.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw8624_osc_rtp_24K_5s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_osc_rtp_24K_5s.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw8624_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw8624_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_lighthouse.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw8624_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_silk.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/aw87xxx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_acf.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/conninfra.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/conninfra.cfg \
    vendor/infinix/X6739/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/infinix/X6739/proprietary/vendor/firmware/focaltech_ts_fw_00.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_00.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_aud_ctos.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_aud_ctos.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_aud_pwm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_aud_pwm.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_aud_single_dir.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_aud_single_dir.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_aud_stoc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_aud_stoc.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_allon.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_allon.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_charging.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_charging.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_double_flash.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_double_flash.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_flash.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_flash.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_fully_charged.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_fully_charged.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_incoming.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_incoming.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_incoming_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_incoming_2.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_incoming_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_incoming_3.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_inform_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_inform_3.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_dyna_test.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_dyna_test.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_static_game.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_static_game.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_static_poweron_meteor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_static_poweron_meteor.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_static_poweron_stage1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_static_poweron_stage1.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamp1_static_poweron_stage2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamp1_static_poweron_stage2.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamps_init.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamps_init.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamps_off.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamps_off.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lamps_standby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lamps_standby.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/infinix/X6739/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/infinix/X6739/proprietary/vendor/firmware/soc3_0_patch_wmmcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_patch_wmmcu_1a_1_hdr.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/soc3_0_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_bt_1_1_hdr.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/soc3_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_bt_1a_1_hdr.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/soc3_0_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_1_1_hdr.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/soc3_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_1a_1_hdr.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/soc3_0_ram_mcu_e1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_e1_hdr.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/soc3_0_ram_wifi_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_wifi_1a_1_hdr.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/soc3_0_ram_wmmcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_wmmcu_1a_1_hdr.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/st21nfc_fw7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw7.bin \
    vendor/infinix/X6739/proprietary/vendor/firmware/valhall-1691526.wa:$(TARGET_COPY_OUT_VENDOR)/firmware/valhall-1691526.wa \
    vendor/infinix/X6739/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/infinix/X6739/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/infinix/X6739/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/infinix/X6739/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/infinix/X6739/proprietary/vendor/thh/ta/df1edda8627911e980ae507b9d9a7e7d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/df1edda8627911e980ae507b9d9a7e7d.ta

PRODUCT_PACKAGES += \
    AV1SecureVdecCA \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    libAVCSecureVencCA \
    libTEECommon \
    libadpcmdec_mtk \
    libaedv \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libbwc \
    libcapctrl \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcodec2_mtk_c2store \
    libcodec2_soft_mtk_alacdec \
    libcodec2_soft_mtk_apedec \
    libcodec2_soft_mtk_imaadpcmdec \
    libcodec2_soft_mtk_mp3dec \
    libcodec2_soft_mtk_msadpcmdec \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libfgauge_gm30 \
    libformatter \
    libgz_gp_client \
    libgz_uree \
    libhevce_sb.ca7.android \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libladder \
    libmnetlink_v104 \
    libmp3dec_mtk \
    libmtcloader \
    libmtkares \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtksysutils \
    libperfctl_vendor \
    libsimlock \
    libsimmelock \
    libstagefrighthw \
    libsysenv \
    libthha \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libvpu \
    libvpu5 \
    libmtk_drvb \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    awinic.audio.effect \
    libHEVCdec_sa.ca7.android \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    librcs_interface \
    librcs_volte_core \
    libthermalalgo \
    libvcodec_utility_v3a \
    libvcodecdrv_v3a \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpudv3a_vcodec \
    libvt_custom \
    vendor.mediatek.hardware.rcs@2.0 \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    APUWareXrpServer_v2 \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    gc02m1_mipi_raw_IdxMgr \
    gc02m1_mipi_raw_tuning \
    gc02m1macro_mipi_raw_IdxMgr \
    gc02m1macro_mipi_raw_tuning \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.sensors@2.X-subhal-mediatek \
    audio.primary.mt6893 \
    audio.r_submix.mt6893 \
    gf_fingerprint.default \
    gps.default \
    hwcomposer.mt6893 \
    kmsetkey.trustonic \
    libMcGatekeeper \
    libSoftGatekeeper \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    vulkan.mali \
    sensors.mt6893 \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    lbs_hidl_service-impl \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist.models \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.aishutter.models \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_gc02m1macromipiraw_Flash_Capture \
    libCamera_gc02m1macromipiraw_Scene_Capture \
    libCamera_gc02m1macromipiraw_Scene_Preview \
    libCamera_gc02m1mipiraw_Scene_Capture \
    libCamera_gc02m1mipiraw_Scene_Preview \
    libCamera_pblcgc02m1macromipiraw_Flash_Capture \
    libCamera_pblcgc02m1macromipiraw_Scene_Capture \
    libCamera_pblcgc02m1macromipiraw_Scene_Preview \
    libCamera_pblcgc02m1mipiraw_Scene_Capture \
    libCamera_pblcgc02m1mipiraw_Scene_Preview \
    libCamera_pblcs5kgd2spmipiraw_360VideoHDR_1080P \
    libCamera_pblcs5kgd2spmipiraw_360VideoHDR_720P \
    libCamera_pblcs5kgd2spmipiraw_3rd_Capture_FD \
    libCamera_pblcs5kgd2spmipiraw_3rd_Preview_FD \
    libCamera_pblcs5kgd2spmipiraw_Capture_Zoom1 \
    libCamera_pblcs5kgd2spmipiraw_Default_Capture \
    libCamera_pblcs5kgd2spmipiraw_Default_Preview \
    libCamera_pblcs5kgd2spmipiraw_Default_Video \
    libCamera_pblcs5kgd2spmipiraw_FaceBeauty \
    libCamera_pblcs5kgd2spmipiraw_FilmVideo \
    libCamera_pblcs5kgd2spmipiraw_Flash_Capture \
    libCamera_pblcs5kgd2spmipiraw_HDR_MINUS_EV \
    libCamera_pblcs5kgd2spmipiraw_LLHDR_0EV \
    libCamera_pblcs5kgd2spmipiraw_NHDR_0EV \
    libCamera_pblcs5kgd2spmipiraw_Preview_Zoom1 \
    libCamera_pblcs5kgd2spmipiraw_Production_Capture \
    libCamera_pblcs5kgd2spmipiraw_Production_Preview \
    libCamera_pblcs5kgd2spmipiraw_Resolution \
    libCamera_pblcs5kgd2spmipiraw_Resolution_zoom \
    libCamera_pblcs5kgd2spmipiraw_Scene_Capture \
    libCamera_pblcs5kgd2spmipiraw_Scene_Capture_4cell \
    libCamera_pblcs5kgd2spmipiraw_Scene_Panorama \
    libCamera_pblcs5kgd2spmipiraw_Scene_Preview \
    libCamera_pblcs5kgd2spmipiraw_ShortVideo \
    libCamera_pblcs5kgd2spmipiraw_ShortVideo_Zoom1 \
    libCamera_pblcs5kgd2spmipiraw_SlimVideo_120Fps \
    libCamera_pblcs5kgd2spmipiraw_SlimVideo_240Fps \
    libCamera_pblcs5kgd2spmipiraw_SuperNight \
    libCamera_pblcs5kgd2spmipiraw_Super_Flash_Screen \
    libCamera_pblcs5kgd2spmipiraw_Super_Flash_ScreenTorch \
    libCamera_pblcs5kgd2spmipiraw_Super_Flash_torch \
    libCamera_pblcs5kgd2spmipiraw_Video_1080P_30fps \
    libCamera_pblcs5kgd2spmipiraw_Video_1080P_60fps \
    libCamera_pblcs5kgd2spmipiraw_Video_2K \
    libCamera_pblcs5kgd2spmipiraw_Video_720P \
    libCamera_pblcs5kgd2spmipiraw_Video_Zoom1 \
    libCamera_pblcs5khm6sxmipiraw_360HDR \
    libCamera_pblcs5khm6sxmipiraw_3rd_Capture \
    libCamera_pblcs5khm6sxmipiraw_3rd_Capture_FD \
    libCamera_pblcs5khm6sxmipiraw_3rd_Preview \
    libCamera_pblcs5khm6sxmipiraw_3rd_Preview_FD \
    libCamera_pblcs5khm6sxmipiraw_Boken_Capture \
    libCamera_pblcs5khm6sxmipiraw_Capture_Zoom1 \
    libCamera_pblcs5khm6sxmipiraw_Capture_Zoom2 \
    libCamera_pblcs5khm6sxmipiraw_Capture_Zoom2_TDT \
    libCamera_pblcs5khm6sxmipiraw_Flash_Capture \
    libCamera_pblcs5khm6sxmipiraw_NHDR_0EV \
    libCamera_pblcs5khm6sxmipiraw_Preview_Zoom1 \
    libCamera_pblcs5khm6sxmipiraw_Preview_Zoom2 \
    libCamera_pblcs5khm6sxmipiraw_Preview_Zoom2_TDT \
    libCamera_pblcs5khm6sxmipiraw_Preview_Zoom3_TDT \
    libCamera_pblcs5khm6sxmipiraw_Pro_Capture \
    libCamera_pblcs5khm6sxmipiraw_Pro_scene \
    libCamera_pblcs5khm6sxmipiraw_Resolution \
    libCamera_pblcs5khm6sxmipiraw_Resolution_zoom \
    libCamera_pblcs5khm6sxmipiraw_Scene_Capture \
    libCamera_pblcs5khm6sxmipiraw_Scene_Capture_4cell \
    libCamera_pblcs5khm6sxmipiraw_Scene_Capture_Remosaic \
    libCamera_pblcs5khm6sxmipiraw_Scene_PreFlash_Preview \
    libCamera_pblcs5khm6sxmipiraw_Scene_Preview \
    libCamera_pblcs5khm6sxmipiraw_SuperNight \
    libCamera_pblcs5khm6sxmipiraw_Super_Flash \
    libCamera_pblcs5khm6sxmipiraw_Video \
    libCamera_pblcs5khm6sxmipiraw_Video_1080p \
    libCamera_pblcs5khm6sxmipiraw_Video_120fps \
    libCamera_pblcs5khm6sxmipiraw_Video_240fps \
    libCamera_pblcs5khm6sxmipiraw_Video_2k \
    libCamera_pblcs5khm6sxmipiraw_Video_EIS \
    libCamera_pblcs5khm6sxmipiraw_Video_Zoom1 \
    libCamera_pblcs5khm6sxmipiraw_Video_Zoom2 \
    libCamera_pbrogc02m1macromipiraw_Flash_Capture \
    libCamera_pbrogc02m1macromipiraw_Scene_Capture \
    libCamera_pbrogc02m1macromipiraw_Scene_Preview \
    libCamera_pbrogc02m1mipiraw_Scene_Capture \
    libCamera_pbrogc02m1mipiraw_Scene_Preview \
    libCamera_pbros5kgd2spmipiraw_360VideoHDR_1080P \
    libCamera_pbros5kgd2spmipiraw_360VideoHDR_720P \
    libCamera_pbros5kgd2spmipiraw_3rd_Capture_FD \
    libCamera_pbros5kgd2spmipiraw_3rd_Preview_FD \
    libCamera_pbros5kgd2spmipiraw_Capture_Zoom1 \
    libCamera_pbros5kgd2spmipiraw_Default_Capture \
    libCamera_pbros5kgd2spmipiraw_Default_Preview \
    libCamera_pbros5kgd2spmipiraw_Default_Video \
    libCamera_pbros5kgd2spmipiraw_FaceBeauty \
    libCamera_pbros5kgd2spmipiraw_FilmVideo \
    libCamera_pbros5kgd2spmipiraw_Flash_Capture \
    libCamera_pbros5kgd2spmipiraw_HDR_MINUS_EV \
    libCamera_pbros5kgd2spmipiraw_LLHDR_0EV \
    libCamera_pbros5kgd2spmipiraw_NHDR_0EV \
    libCamera_pbros5kgd2spmipiraw_Preview_Zoom1 \
    libCamera_pbros5kgd2spmipiraw_Resolution \
    libCamera_pbros5kgd2spmipiraw_Resolution_zoom \
    libCamera_pbros5kgd2spmipiraw_Scene_Capture \
    libCamera_pbros5kgd2spmipiraw_Scene_Capture_4cell \
    libCamera_pbros5kgd2spmipiraw_Scene_Preview \
    libCamera_pbros5kgd2spmipiraw_ShortVideo \
    libCamera_pbros5kgd2spmipiraw_ShortVideo_Zoom1 \
    libCamera_pbros5kgd2spmipiraw_SlimVideo_120Fps \
    libCamera_pbros5kgd2spmipiraw_SlimVideo_240Fps \
    libCamera_pbros5kgd2spmipiraw_SuperNight \
    libCamera_pbros5kgd2spmipiraw_Super_Flash \
    libCamera_pbros5kgd2spmipiraw_Super_Flash_Screen \
    libCamera_pbros5kgd2spmipiraw_Video_1080P_30fps \
    libCamera_pbros5kgd2spmipiraw_Video_1080P_60fps \
    libCamera_pbros5kgd2spmipiraw_Video_720P \
    libCamera_pbros5kgd2spmipiraw_Video_Zoom1 \
    libCamera_pbros5khm6sxmipiraw_360HDR \
    libCamera_pbros5khm6sxmipiraw_3rd_Capture \
    libCamera_pbros5khm6sxmipiraw_3rd_Capture_FD \
    libCamera_pbros5khm6sxmipiraw_3rd_Preview \
    libCamera_pbros5khm6sxmipiraw_3rd_Preview_FD \
    libCamera_pbros5khm6sxmipiraw_Boken_Capture \
    libCamera_pbros5khm6sxmipiraw_Capture_Zoom1 \
    libCamera_pbros5khm6sxmipiraw_Capture_Zoom2 \
    libCamera_pbros5khm6sxmipiraw_Flash_Capture \
    libCamera_pbros5khm6sxmipiraw_NHDR_0EV \
    libCamera_pbros5khm6sxmipiraw_Preview_Zoom1 \
    libCamera_pbros5khm6sxmipiraw_Preview_Zoom2 \
    libCamera_pbros5khm6sxmipiraw_Pro_Capture \
    libCamera_pbros5khm6sxmipiraw_Pro_scene \
    libCamera_pbros5khm6sxmipiraw_Resolution \
    libCamera_pbros5khm6sxmipiraw_Resolution_zoom \
    libCamera_pbros5khm6sxmipiraw_Scene_Capture \
    libCamera_pbros5khm6sxmipiraw_Scene_Capture_4cell \
    libCamera_pbros5khm6sxmipiraw_Scene_Capture_Remosaic \
    libCamera_pbros5khm6sxmipiraw_Scene_PreFlash_Preview \
    libCamera_pbros5khm6sxmipiraw_Scene_Preview \
    libCamera_pbros5khm6sxmipiraw_SuperNight \
    libCamera_pbros5khm6sxmipiraw_Super_Flash \
    libCamera_pbros5khm6sxmipiraw_Video \
    libCamera_pbros5khm6sxmipiraw_Video_1080p \
    libCamera_pbros5khm6sxmipiraw_Video_120fps \
    libCamera_pbros5khm6sxmipiraw_Video_240fps \
    libCamera_pbros5khm6sxmipiraw_Video_2k \
    libCamera_pbros5khm6sxmipiraw_Video_EIS \
    libCamera_pbros5khm6sxmipiraw_Video_Zoom1 \
    libCamera_pbros5khm6sxmipiraw_Video_Zoom2 \
    libCamera_s5kgd2spmipiraw_360VideoHDR_1080P \
    libCamera_s5kgd2spmipiraw_360VideoHDR_720P \
    libCamera_s5kgd2spmipiraw_3rd_Capture_FD \
    libCamera_s5kgd2spmipiraw_3rd_Preview_FD \
    libCamera_s5kgd2spmipiraw_Capture_Zoom1 \
    libCamera_s5kgd2spmipiraw_Default_Capture \
    libCamera_s5kgd2spmipiraw_Default_Preview \
    libCamera_s5kgd2spmipiraw_Default_Video \
    libCamera_s5kgd2spmipiraw_FaceBeauty \
    libCamera_s5kgd2spmipiraw_FilmVideo \
    libCamera_s5kgd2spmipiraw_Flash_Capture \
    libCamera_s5kgd2spmipiraw_HDR_MINUS_EV \
    libCamera_s5kgd2spmipiraw_LLHDR_0EV \
    libCamera_s5kgd2spmipiraw_NHDR_0EV \
    libCamera_s5kgd2spmipiraw_Preview_Zoom1 \
    libCamera_s5kgd2spmipiraw_Production_Capture \
    libCamera_s5kgd2spmipiraw_Production_Preview \
    libCamera_s5kgd2spmipiraw_Resolution \
    libCamera_s5kgd2spmipiraw_Resolution_zoom \
    libCamera_s5kgd2spmipiraw_Scene_Capture \
    libCamera_s5kgd2spmipiraw_Scene_Capture_4cell \
    libCamera_s5kgd2spmipiraw_Scene_Panorama \
    libCamera_s5kgd2spmipiraw_Scene_Preview \
    libCamera_s5kgd2spmipiraw_ShortVideo \
    libCamera_s5kgd2spmipiraw_ShortVideo_Zoom1 \
    libCamera_s5kgd2spmipiraw_SlimVideo_120Fps \
    libCamera_s5kgd2spmipiraw_SlimVideo_240Fps \
    libCamera_s5kgd2spmipiraw_SuperNight \
    libCamera_s5kgd2spmipiraw_Super_Flash_Screen \
    libCamera_s5kgd2spmipiraw_Super_Flash_ScreenTorch \
    libCamera_s5kgd2spmipiraw_Super_Flash_torch \
    libCamera_s5kgd2spmipiraw_Video_1080P_30fps \
    libCamera_s5kgd2spmipiraw_Video_1080P_60fps \
    libCamera_s5kgd2spmipiraw_Video_2K \
    libCamera_s5kgd2spmipiraw_Video_720P \
    libCamera_s5kgd2spmipiraw_Video_Zoom1 \
    libCamera_s5khm6sxmipiraw_360HDR \
    libCamera_s5khm6sxmipiraw_3rd_Capture \
    libCamera_s5khm6sxmipiraw_3rd_Capture_FD \
    libCamera_s5khm6sxmipiraw_3rd_Preview \
    libCamera_s5khm6sxmipiraw_3rd_Preview_FD \
    libCamera_s5khm6sxmipiraw_Boken_Capture \
    libCamera_s5khm6sxmipiraw_Capture_Zoom1 \
    libCamera_s5khm6sxmipiraw_Capture_Zoom2 \
    libCamera_s5khm6sxmipiraw_Capture_Zoom2_TDT \
    libCamera_s5khm6sxmipiraw_Flash_Capture \
    libCamera_s5khm6sxmipiraw_NHDR_0EV \
    libCamera_s5khm6sxmipiraw_Preview_Zoom1 \
    libCamera_s5khm6sxmipiraw_Preview_Zoom2 \
    libCamera_s5khm6sxmipiraw_Preview_Zoom2_TDT \
    libCamera_s5khm6sxmipiraw_Preview_Zoom3_TDT \
    libCamera_s5khm6sxmipiraw_Pro_Capture \
    libCamera_s5khm6sxmipiraw_Pro_scene \
    libCamera_s5khm6sxmipiraw_Resolution \
    libCamera_s5khm6sxmipiraw_Resolution_zoom \
    libCamera_s5khm6sxmipiraw_Scene_Capture \
    libCamera_s5khm6sxmipiraw_Scene_Capture_4cell \
    libCamera_s5khm6sxmipiraw_Scene_Capture_Remosaic \
    libCamera_s5khm6sxmipiraw_Scene_PreFlash_Preview \
    libCamera_s5khm6sxmipiraw_Scene_Preview \
    libCamera_s5khm6sxmipiraw_SuperNight \
    libCamera_s5khm6sxmipiraw_Super_Flash \
    libCamera_s5khm6sxmipiraw_Video \
    libCamera_s5khm6sxmipiraw_Video_1080p \
    libCamera_s5khm6sxmipiraw_Video_120fps \
    libCamera_s5khm6sxmipiraw_Video_240fps \
    libCamera_s5khm6sxmipiraw_Video_2k \
    libCamera_s5khm6sxmipiraw_Video_EIS \
    libCamera_s5khm6sxmipiraw_Video_Zoom1 \
    libCamera_s5khm6sxmipiraw_Video_Zoom2 \
    libDefaultFpsActor \
    libFrameRecord \
    libImageEval \
    libJpgEncPipe \
    libMcClient \
    libMtkSpeechEnh \
    libNoFpsActor \
    libNvLutEffect \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTranASD \
    libTranArcFilter \
    libTranArcFlashNew \
    libTranArcHDR \
    libTranArcLLHDR \
    libTranArcNightHawk \
    libTranAutoColorLevel \
    libTranBefMakeup \
    libTranColorEnhance \
    libTranDenoise \
    libTranExtImgProc \
    libTranExtImgThread \
    libTranEyeDetect \
    libTranGenderDetect \
    libTranHumanLight \
    libTranITDFaceBeauty \
    libTranMSFilter \
    libTranMagicSky \
    libTranMegDualDepth \
    libTranMegDualDepthtoBokeh \
    libTranMegDualRefocus \
    libTranPlatHW \
    libTranSTPRRepair \
    libTranSTSingleBlur \
    libTranSlimBody \
    libTranSmartDetection \
    libTranSuperResolution \
    libTranVideoFilter \
    libTran_Log \
    libTran_mtkPowerAPI \
    libWaterMarkProc \
    lib_bsscore \
    lib_iir \
    lib_speech_enh \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaidepth_tuning \
    libainrcore \
    libalsautils-v31 \
    libamipengine \
    libanc_dc_base \
    libanc_hdr \
    libanc_hdr_adapter_s5kgd2sp_17201766_front_d1300 \
    libanc_hdr_adapter_s5khm6sx_17201842_back_d1300 \
    libancbase \
    libancbase_848 \
    libappgamepq \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_night_hawk \
    libarcsoft_torch_portrait_night \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libc++_shared \
    libcalculatesharpness \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam3_tranelapsedtime \
    libcam3_tranpriorityctrl \
    libcam3_transerverengine \
    libcam3atms_profiles \
    libcamalgo.3dnr \
    libcamalgo.aibc \
    libcamalgo.aihdr \
    libcamalgo.ainr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.utility \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcameracustom \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcolorenhance_64 \
    libcolorlevel \
    libcomposer_ext \
    libconnfem \
    libcs_cs35l45_intf \
    libcustom_nvram \
    libcvsd_mtk \
    libdenoise \
    libdip_drv \
    libdip_postproc \
    libdre \
    libeffect_hal \
    libeffecthal.base \
    libeyedetector \
    libfacesattribute \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libfile_op \
    libforkexecwrap \
    libgamehdr \
    libged \
    libgf_hal \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libheichal \
    libhfmanager \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libitdfacebeauty \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkmsetkey \
    libksensor \
    liblpcnr \
    libmagicsky_64 \
    libmfllcore \
    libmipc \
    libmmagent \
    libmml \
    libmorpho_HDSR \
    libmorpho_video_stabilizer \
    libmpbase \
    libmsbc_mtk \
    libmsnr \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_3rdparty.thread \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkisp_metadata \
    libmtklimiter_vendor \
    libmtkmipc-ril \
    libmtknetcap \
    libmtkrilutils \
    libmtkshifter_vendor \
    libmtktinyxml \
    libmtkutils \
    libmvpu_config_data \
    libneuroeara \
    libneuron_adapter \
    libneuron_graph_delegate.mtk \
    libneuron_platform \
    libneuron_wrapper \
    libneuropilot_hal_utils \
    libnir_neon_driver_ndk.mtk.vndk \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    liboemcrypto \
    libportrait_repair_ppl3_ocl \
    libpq_cust_base \
    libpqframework \
    libpqparamparser \
    libpqpconfig \
    libratconfig \
    librgbwlightsensor \
    librilfusion \
    librt_extamp_intf \
    libsegmention \
    libsegmentionPre \
    libsensor_custom \
    libsmartdetector \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libst_mobile \
    libstblur_capture_api \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libtf_asd_lib \
    libtflite_mtk \
    libtflite_native_gainference \
    libtflite_native_inference \
    libtflite_native_seginference \
    libtlcWidevineModularDrm \
    libtneclient \
    libtrancamJsonConvertor \
    libtrancam_filelockmgr \
    libtranlog \
    libtranssion_bodybeauty \
    libtranssion_cal \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvendor.goodix.hardware.biometrics.fingerprint@2.1 \
    libvia-ril \
    libviamipc-ril \
    libvideofilter_cl_64 \
    libwa_depth \
    libwa_dof \
    libwa_refocus \
    libwa_rtdof \
    libwifi-hal-mtk \
    libwpfa \
    libwvhidl \
    libwvdrmengine \
    arm.graphics-V1-ndk_platform \
    arm.graphics-ndk_platform \
    libDR \
    libaiselector \
    libdpframework \
    libgpudataproducer \
    libmnl \
    libneuron_platform.vpu \
    libneuron_runtime.5 \
    libnir_neon_driver \
    libpq_prot \
    mtk000_mipi_raw_IdxMgr \
    libmtkcam_streaminfo_plugin-p1stt \
    pblcgc02m1_mipi_raw_IdxMgr \
    pblcgc02m1_mipi_raw_tuning \
    pblcgc02m1macro_mipi_raw_IdxMgr \
    pblcgc02m1macro_mipi_raw_tuning \
    pblcs5kgd2sp_mipi_raw_IdxMgr \
    pblcs5kgd2sp_mipi_raw_tuning \
    pblcs5khm6sx_mipi_raw_IdxMgr \
    pblcs5khm6sx_mipi_raw_tuning \
    pbrogc02m1_mipi_raw_IdxMgr \
    pbrogc02m1_mipi_raw_tuning \
    pbrogc02m1macro_mipi_raw_IdxMgr \
    pbrogc02m1macro_mipi_raw_tuning \
    pbros5kgd2sp_mipi_raw_IdxMgr \
    pbros5kgd2sp_mipi_raw_tuning \
    pbros5khm6sx_mipi_raw_IdxMgr \
    pbros5khm6sx_mipi_raw_tuning \
    s5kgd2sp_mipi_raw_IdxMgr \
    s5kgd2sp_mipi_raw_tuning \
    s5khm6sx_mipi_raw_IdxMgr \
    s5khm6sx_mipi_raw_tuning \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.xrp@2.0 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.biometrics.fingerprint@2.1 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.transsion.hardware.trancam.trancamserver@1.0 \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    libmtk_vt_wrapper \
    libmtkperf_client_system_ext \
    libvcodec_cap \
    libvcodec_capenc \
    vendor.mediatek.hardware.mtkpower-V1-ndk \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    vendor.mediatek.hardware.videotelephony@1.0 \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libsignal \
    libsink-mtk \
    libsource \
    libvt_avsync \
    ImsService \
    mediatek-carrier-config-manager \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-ims-extension-plugin \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    android.hardware.biometrics.fingerprint@2.1-service-mediatek.xml \
    android.hardware.biometrics.fingerprint@2.3-service.transsion.xml \
    android.hardware.neuralnetworks@1.3-service-mtk-mdla-dsp-gpu.xml \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    lbs_hidl_service@1.0.xml \
    manifest.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_media_c2_V1_2_default.xml \
    vendor.transsion.hardware.trancam.trancamserver@1.0.xml \
    ccci_mdinit \
    ccci_rpcd \
    conninfra_loader \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.biometrics.fingerprint@2.1-service-mediatek \
    android.hardware.biometrics.fingerprint@2.3-service.transsion \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.1-service.trustonic \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks@1.3-service-mtk-neuron \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.sensors@2.0-service.multihal-mediatek \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.transsion.hardware.trancam.trancamserver@1.0-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    jpegtool \
    kmsetkey_ca.trustonic \
    lbs_hidl_service \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    mcDriverDaemon \
    mnld \
    mt6660_calibration \
    mtk_agpsd \
    muxreport \
    netdagent \
    nvram_daemon \
    rcs_volte_stack \
    rt5512_calibration \
    rttv \
    thermal \
    thermal_core \
    thermal_intf \
    thermal_manager \
    thermalloadalgod \
    v3avpud \
    volte_clientapi_ua \
    volte_rcs_ua \
    wifi_dump \
    wlan_assistant \
    vtservice

PRODUCT_PACKAGES += \
    vendor_lib_libmtk_drvb_so \
    vendor_lib64_egl_libGLES_mali_so \
    vendor_lib64_hw_vulkan_mt6893_so \
    vendor_lib64_hw_kmsetkey_default_so \
    vendor_lib64_hw_gatekeeper_trustonic_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_hw_android_hardware_graphics_allocator@4_0-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib64_hw_vulkan_mali_so \
    vendor_lib64_arm_graphics-V1-ndk_platform_so \
    vendor_lib64_arm_graphics-ndk_platform_so \
    vendor_lib64_libDR_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libgpudataproducer_so \
    vendor_lib64_libmnl_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libneuron_platform_vpu_so \
    vendor_lib64_libneuron_runtime_5_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_prot_so
